
package views;

import controllers.ControllerConsulta;
import controllers.ControllerPacientes;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import models.Pacientes;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hemilio
 */
public class CadastroConsulta extends javax.swing.JFrame {
    private String tipo;
    private int id;
    private String dataConsulta;
    private String cpfPaciente;
    
    private String nome;
    private String nascimento;
    private String sexo;
    private ResultSet rs;
    
    
    public CadastroConsulta(){
        
    }
    
    public CadastroConsulta(String tipo) {
        this.tipo = tipo;
        this.rs = null;
        initComponents();
//        System.out.println(tipo);
        if (tipo == "s")
            btnExcluir.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtDataConsulta = new javax.swing.JFormattedTextField();
        btnBuscarCpf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdConsulta = new javax.swing.JTextField();
        btnSalvarAlteracoes = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        btnBuscarConsulta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFerramentas = new javax.swing.JMenu();
        menuCadCon = new javax.swing.JMenuItem();
        menuCadPac = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPF Paciente:");

        jLabel2.setText("Nome:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtDataConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataConsulta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnBuscarCpf.setText("Buscar");
        btnBuscarCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCpfActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Consulta:");

        jLabel4.setText("Id Consulta:");

        txtIdConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdConsultaActionPerformed(evt);
            }
        });

        btnSalvarAlteracoes.setText("Salvar Alterações");
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setForeground(new java.awt.Color(255, 0, 51));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel5.setText("Gênero:");

        lblGenero.setText("sexo");

        jLabel6.setText("Nascimento:");

        lblDataNascimento.setText("data");

        jLabel7.setText("Idade:");

        lblIdade.setText("anos");

        lblNome.setText("nome");

        btnBuscarConsulta.setText("Buscar");
        btnBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConsultaActionPerformed(evt);
            }
        });

        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblConsultas);

        menuFerramentas.setText("Ferramentas");

        menuCadCon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        menuCadCon.setText("Cadastrar Paciente");
        menuCadCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadConActionPerformed(evt);
            }
        });
        menuFerramentas.add(menuCadCon);

        menuCadPac.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        menuCadPac.setText("Cadastrar Consulta");
        menuCadPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadPacActionPerformed(evt);
            }
        });
        menuFerramentas.add(menuCadPac);

        jMenuBar1.add(menuFerramentas);

        menuAjuda.setText("Ajuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAjuda.add(jMenuItem1);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataNascimento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNome))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCpf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGenero))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdade))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDataConsulta, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarConsulta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvarAlteracoes)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblGenero))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDataNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblIdade))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarConsulta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnSalvarAlteracoes)
                    .addComponent(btnExcluir))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdConsultaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        dataConsulta = dataParaBanco(txtDataConsulta.getText());
        cpfPaciente = txtCpf.getText();
        
        ControllerConsulta cc = new ControllerConsulta(dataConsulta, cpfPaciente);
        cc.salvar();
        
        btnBuscarCpfActionPerformed(evt);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void menuCadConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadConActionPerformed
        CadastroPaciente cp = new CadastroPaciente(tipo);
        cp.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_menuCadConActionPerformed

    private void menuCadPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadPacActionPerformed
        CadastroConsulta cc = new CadastroConsulta(tipo);
        cc.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_menuCadPacActionPerformed

    private void btnBuscarCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCpfActionPerformed
        cpfPaciente = txtCpf.getText();
        
        ControllerPacientes cp = new ControllerPacientes(nome, cpfPaciente, nascimento, sexo);
        rs = cp.buscar();
        
        if(rs != null){
            try {
                rs.next();
            
                lblNome.setText(rs.getString("nome"));
                lblDataNascimento.setText(dataParaBanco(tracoBarra(rs.getString("nascimento"))));
                
                if(rs.getString("sexo").equalsIgnoreCase("F"))
                    lblGenero.setText("Feminino");
                else
                    lblGenero.setText("Masculino");
                
                nascimento = dataParaBanco(tracoBarra(rs.getString("nascimento")));
                String idade = String.valueOf(idade(nascimento));
                
                lblIdade.setText(idade);
                
                txtDataConsulta.setText("");
                txtIdConsulta.setText("");
                
                                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
        
        rs = cp.buscarConsultas();
        
        if(rs != null){
            try {
                tblConsultas.setModel(DbUtils.resultSetToTableModel(rs));
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_btnBuscarCpfActionPerformed

    private void btnBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConsultaActionPerformed
        id = Integer.parseInt(txtIdConsulta.getText());
        
        ControllerConsulta cc = new ControllerConsulta(id);
        rs = cc.buscar();
        
        if(rs != null){
            try {
                rs.next();
                lblNome.setText(rs.getString("paciente.nome"));
                
                if(rs.getString("sexo").equalsIgnoreCase("F"))
                    lblGenero.setText("Feminino");
                else
                    lblGenero.setText("Masculino");
                
                lblDataNascimento.setText(dataParaBanco(tracoBarra(rs.getString("nascimento"))));
                nascimento = dataParaBanco(tracoBarra(rs.getString("nascimento")));
                String idade = String.valueOf(idade(nascimento));
                lblIdade.setText(idade);
                
                txtCpf.setText(rs.getString("cpf"));
                
                txtDataConsulta.setText(dataParaBanco(tracoBarra(rs.getString("dataConsulta"))));
                
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_btnBuscarConsultaActionPerformed

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        id = Integer.parseInt(txtIdConsulta.getText());
        dataConsulta = dataParaBanco(txtDataConsulta.getText());
        
        ControllerConsulta cc = new ControllerConsulta(id, dataConsulta);
        cc.atualizar();
        
        btnBuscarCpfActionPerformed(evt);
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String sobre = "Produzido por: Hemílio Lauro e Gustavo de Paula\n"
                + "Disciplina: Programação orientada a objetos\n"
                + "Professor: Robson\n"
                + "Ano: 2019";
        
        JOptionPane.showMessageDialog(rootPane, sobre);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        id = Integer.parseInt(txtIdConsulta.getText());
        
        ControllerConsulta cc = new ControllerConsulta(id);
        cc.excluir();
        
        btnBuscarCpfActionPerformed(evt);
    }//GEN-LAST:event_btnExcluirActionPerformed

    
    private String dataParaBanco(String d){
        String data = d; 
        String[] s = data.split("/"); 
        String novaData = s[2]+"/"+s[1]+"/"+s[0];
        
        return novaData;
    }
    
    private String tracoBarra(String d){
        String barra = d.replaceAll("-", "/");
        
        return barra;
    }
    
    
    public int idade(String nascimento) throws ParseException{
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        Date inicial = sdf.parse(nascimento);
        Date atual = new Date();
        
        long diferencaMillis = Math.abs(atual.getTime() - inicial.getTime());
        
        long diff = TimeUnit.DAYS.convert(diferencaMillis, TimeUnit.MILLISECONDS);
        
        int anos = (int) Math.abs(diff/365);
        
        return anos;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarConsulta;
    private javax.swing.JButton btnBuscarCpf;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuCadCon;
    private javax.swing.JMenuItem menuCadPac;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JTable tblConsultas;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataConsulta;
    private javax.swing.JTextField txtIdConsulta;
    // End of variables declaration//GEN-END:variables
}
